"""
Django settings for mybook project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
# SITE_ROOT=os.path.join(os.path.abspath(os.path.dirname(__file__)),'..')
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# STATIC_ROOT = os.path.join(SITE_ROOT,'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')6k_im6r#2=xicnr==%!z#3wo3*2c6!@zjbn+de73gxi*3nl^a'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG =True

ALLOWED_HOSTS = ['*',]



# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'DjangoUeditor',

)



MIDDLEWARE_CLASSES = (
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
    # 'myapp.middleware.MyMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware'
    # 'django.middleware.cache.FetchFromCacheMiddleware',
)

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
    },
]
CACHES = {
    'default':
        { 'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
          'LOCATION': os.path.join(BASE_DIR,'django.cache'),
          'TIMEOUT': 2,
          'OPTIONS': { 'MAX_ENTRIES': 1000 }
          }
}

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # 163邮箱服务器地址
EMAIL_PORT = 25 # smtp端口

#发送邮件的邮箱
EMAIL_HOST_USER = 'a18153859123@163.com'

#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'abc123'
#收件人看到的发件人
EMAIL_FROM = 'python<a18153859123@163.com>'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

STATIC_URL = '/static/'#配置到/static/开头的都表示静态文件，相当于路由访问静态文件
STATICFILES_DIRS = [os.path.join(BASE_DIR),'static']
# STATIC_ROOT = (
#     os.path.join(BASE_DIR, 'static').replace('\\', '/')
# )


MEDIA_ROOT=os.path.join(BASE_DIR,"static/media") # 配置图片保存在static/media/目录下
MEDIA_URL = "/static/media/" # 访问图片路径，如果不设置，在admin后台中预览会找不到图片。


THUMB_DIR=os.path.join(BASE_DIR,"static/media/thumb")#设置缩略图路径

#
# STATIC_URL = '/static/'#配置到 /STATIC/开头的一个多表示静态文件,相当于路由访问静态文件
# STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
# print(STATICFILES_DIRS)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

USE_TZ = False
SESSION_ENGINE='django.contrib.sessions.backends.cached_db'
SESSION_COOKIE_AGE=60*60*24 #设置session时效24小时  60*30 =30分钟。

